### PR TITLE
Fixes for Virtual Directories

### PR DESCRIPTION
**Pull request by alex-training**
Example for Archetype https://github.com/kgiszewski/Archetype/pull/283/files

### CODE REVIEW

**Comment by alex-training** [comment]
Hi @dawoe !
I've made a small fix, please take a look

**Comment by dawoe** [comment]
Hi Alex,

Will have a look if this doesn't break when not in virtual directories. If that works okay. I'll merge it and put up a new release.

Dave

**Review by dawoe — APPROVED** [review]
Tested it and also works when not in virtual directories. So will merge

**Comment by dawoe** [comment]
The release of version 1.0.2 is on nuget and on our.umbraco.org

**Pull request merged**
